# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: lint
lint:
	build/run-lint-check.sh

.PHONY: unit-test
unit-test:
	go test ./... -v -coverprofile cover.out
